version: '3.8'
services:
  frontend:
      container_name: frontend
      build:
        context: ./frontend
        dockerfile: Dockerfile
      ports:
        - 3000:80
      depends_on:
        - backend
      links:
        - backend
  backend:
      container_name: backend
      build:
        context: ./backend
        dockerfile: Dockerfile
      environment:
        - DEV_POSTGRES_HOST=db
        - DEV_POSTGRES_DB=assets
        - DEV_DEBUG=true
        - DEV_SECRET_KEY=TOJAZMiFQOq1PIoImUaltg
        - DEV_POSTGRES_USER=dbmanager
        - DEV_POSTGRES_PASSWORD=dbmanager
        - PROD_POSTGRES_HOST=db
        - PROD_POSTGRES_USER=dbmanager
        - PROD_POSTGRES_PASSWORD=dbmanager
        - PROD_POSTGRES_DB=assets
        - POSTGRES_DATABASE_URI=postgresql://dbmanager:dbmanager@db:5432/testing_assets
      volumes:
        - ./backend:/usr/src/repo-app
      ports:
        - 5000:5000
      expose:
        - 5000
      depends_on:
        - db
  db:
    container_name: db
    build:
        context: ./db
        dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5438:5432
    expose:
      - 5438
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local